services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  keycloak:
    image: keycloak/keycloak
    ports:
      - '8081:8080'
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=password'
      - 'KC_HEALTH_ENABLED=true'
    command: start-dev
    volumes:
      - ./keycloak_data:/opt/keycloak/data
